Fixing error
>npm run build

> react-expo@0.0.0 build
> tsc && vite build

tsconfig.json:24:5 - error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.
  Visit https://aka.ms/ts6 for migration information.

24     "baseUrl": ".",
       ~~~~~~~~~

Found 1 error in tsconfig.json:24